# # Create users
# user = User.new(first_name: "Constantine",
#                 last_name: "Nicolaou",
#                 email: "constantin.nicolaou@gmail.com",
#                 admin: true,
#                 password: "password",
#                 password_confirmation: "password")
#
# user.skip_confirmation!
# user.save!
#
# profile = user.profile
# profile.privacy_level = Profile.privacy_options["Open"]
# profile.save

# user_1 = User.new(first_name: "User",
#                   last_name: "One",
#                   email: "user.one@example.com",
#                   password: "password",
#                   password_confirmation: "password")
#
# user_1.skip_confirmation!
# user_1.save!
# user_1.reload
#
# puts user_1.inspect
#
# profile = user_1.profile
# profile.privacy_level = Profile.privacy_options["Open"]
# profile.save
#
# user_2 = User.new(first_name: "User",
#                 last_name: "Two",
#                 email: "user.two@example.com",
#                 password: "password",
#                 password_confirmation: "password")
#
# user_2.skip_confirmation!
# user_2.save!
# user_2.reload
#
# puts user_2.profile.inspect
#
# profile = user_2.profile
# profile.privacy_level = Profile.privacy_options["Open"]
# profile.save

# Create jobs
# job_params = {
#   title: "Software developer",
#   description: "You should be a kick-ass developer",
#   job_description_location: "http://www.keeward.com",
#   location: "LB",
#   remote_ok: true,
#   posted_on: Time.now,
#   posted_to_slack: false,
#   user_id: user.id,
#   company_name: "Keeward",
#   apply_email: "hr@example.com",
#   salary: nil,
#   job_type: "internship",
#   number_of_openings: 1,
#   level: "no_experience"
# }
#
# job = Job.create(job_params)
# job.post_online!


# add skills
skills = [
{name: "A# .NET", is_approved: true},
{name: "A# (Axiom)", is_approved: true},
{name: "A-0 System", is_approved: true},
{name: "A+", is_approved: true},
{name: "A++", is_approved: true},
{name: "ABAP", is_approved: true},
{name: "ABC", is_approved: true},
{name: "ABC ALGOL", is_approved: true},
{name: "ABLE", is_approved: true},
{name: "ABSET", is_approved: true},
{name: "ABSYS", is_approved: true},
{name: "ACC", is_approved: true},
{name: "Accent", is_approved: true},
{name: "Ace DASL", is_approved: true},
{name: "ACL2", is_approved: true},
{name: "ACT-III", is_approved: true},
{name: "Action!", is_approved: true},
{name: "ActionScript", is_approved: true},
{name: "Ada", is_approved: true},
{name: "Adenine", is_approved: true},
{name: "Agda", is_approved: true},
{name: "Agilent VEE", is_approved: true},
{name: "Agora", is_approved: true},
{name: "AIMMS", is_approved: true},
{name: "Alef", is_approved: true},
{name: "ALF", is_approved: true},
{name: "ALGOL 58", is_approved: true},
{name: "ALGOL 60", is_approved: true},
{name: "ALGOL 68", is_approved: true},
{name: "ALGOL W", is_approved: true},
{name: "Alice", is_approved: true},
{name: "Alma-0", is_approved: true},
{name: "AmbientTalk", is_approved: true},
{name: "Amiga E", is_approved: true},
{name: "AMOS", is_approved: true},
{name: "AMPL", is_approved: true},
{name: "APL", is_approved: true},
{name: "App Inventor for Android's visual block language", is_approved: true},
{name: "AppleScript", is_approved: true},
{name: "Arc", is_approved: true},
{name: "ARexx", is_approved: true},
{name: "Argus", is_approved: true},
{name: "AspectJ", is_approved: true},
{name: "Assembly language", is_approved: true},
{name: "ATS", is_approved: true},
{name: "Ateji PX", is_approved: true},
{name: "AutoHotkey", is_approved: true},
{name: "Autocoder", is_approved: true},
{name: "AutoIt", is_approved: true},
{name: "AutoLISP / Visual LISP", is_approved: true},
{name: "Averest", is_approved: true},
{name: "AWK", is_approved: true},
{name: "Axum", is_approved: true},
{name: "B", is_approved: true},
{name: "Babbage", is_approved: true},
{name: "Bash", is_approved: true},
{name: "BASIC", is_approved: true},
{name: "bc", is_approved: true},
{name: "BCPL", is_approved: true},
{name: "BeanShell", is_approved: true},
{name: "Batch (Windows/Dos)", is_approved: true},
{name: "Bertrand", is_approved: true},
{name: "BETA", is_approved: true},
{name: "Bigwig", is_approved: true},
{name: "Bistro", is_approved: true},
{name: "BitC", is_approved: true},
{name: "BLISS", is_approved: true},
{name: "Blue", is_approved: true},
{name: "Bon", is_approved: true},
{name: "Boo", is_approved: true},
{name: "Boomerang", is_approved: true},
{name: "Bourne shell", is_approved: true},
{name: "bash", is_approved: true},
{name: "ksh", is_approved: true},
{name: "BREW", is_approved: true},
{name: "BPEL", is_approved: true},
{name: "C", is_approved: true},
{name: "C--", is_approved: true},
{name: "C++", is_approved: true},
{name: "C#", is_approved: true},
{name: "C/AL", is_approved: true},
{name: "Caché ObjectScript", is_approved: true},
{name: "C Shell", is_approved: true},
{name: "Caml", is_approved: true},
{name: "Candle", is_approved: true},
{name: "Cayenne", is_approved: true},
{name: "CDuce", is_approved: true},
{name: "Cecil", is_approved: true},
{name: "Cel", is_approved: true},
{name: "Cesil", is_approved: true},
{name: "Ceylon", is_approved: true},
{name: "CFEngine", is_approved: true},
{name: "CFML", is_approved: true},
{name: "Cg", is_approved: true},
{name: "Ch", is_approved: true},
{name: "Chapel", is_approved: true},
{name: "CHAIN", is_approved: true},
{name: "Charity", is_approved: true},
{name: "Charm", is_approved: true},
{name: "Chef", is_approved: true},
{name: "CHILL", is_approved: true},
{name: "CHIP-8", is_approved: true},
{name: "chomski", is_approved: true},
{name: "ChucK", is_approved: true},
{name: "CICS", is_approved: true},
{name: "Cilk", is_approved: true},
{name: "CL", is_approved: true},
{name: "Claire", is_approved: true},
{name: "Clarion", is_approved: true},
{name: "Clean", is_approved: true},
{name: "Clipper", is_approved: true},
{name: "CLIST", is_approved: true},
{name: "Clojure", is_approved: true},
{name: "CLU", is_approved: true},
{name: "CMS-2", is_approved: true},
{name: "COBOL", is_approved: true},
{name: "Cobra", is_approved: true},
{name: "CODE", is_approved: true},
{name: "CoffeeScript", is_approved: true},
{name: "Cola", is_approved: true},
{name: "ColdC", is_approved: true},
{name: "ColdFusion", is_approved: true},
{name: "COMAL", is_approved: true},
{name: "Combined Programming Language", is_approved: true},
{name: "COMIT", is_approved: true},
{name: "Common Intermediate Language", is_approved: true},
{name: "Common Lisp", is_approved: true},
{name: "COMPASS", is_approved: true},
{name: "Component Pascal", is_approved: true},
{name: "Constraint Handling Rules", is_approved: true},
{name: "Converge", is_approved: true},
{name: "Cool", is_approved: true},
{name: "Coq", is_approved: true},
{name: "Coral 66", is_approved: true},
{name: "Corn", is_approved: true},
{name: "CorVision", is_approved: true},
{name: "COWSEL", is_approved: true},
{name: "CPL", is_approved: true},
{name: "csh", is_approved: true},
{name: "CSP", is_approved: true},
{name: "Csound", is_approved: true},
{name: "CUDA", is_approved: true},
{name: "Curl", is_approved: true},
{name: "Curry", is_approved: true},
{name: "Cyclone", is_approved: true},
{name: "Cython", is_approved: true},
{name: "D", is_approved: true},
{name: "DASL", is_approved: true},
{name: "Dart", is_approved: true},
{name: "DataFlex", is_approved: true},
{name: "Datalog", is_approved: true},
{name: "DATATRIEVE", is_approved: true},
{name: "dBase", is_approved: true},
{name: "dc", is_approved: true},
{name: "Deesel", is_approved: true},
{name: "Delphi", is_approved: true},
{name: "DCL", is_approved: true},
{name: "DinkC", is_approved: true},
{name: "DIBOL", is_approved: true},
{name: "Dog", is_approved: true},
{name: "Draco", is_approved: true},
{name: "DRAKON", is_approved: true},
{name: "Dylan", is_approved: true},
{name: "DYNAMO", is_approved: true},
{name: "E", is_approved: true},
{name: "E#", is_approved: true},
{name: "Ease", is_approved: true},
{name: "Easy PL/I", is_approved: true},
{name: "Easy Programming Language", is_approved: true},
{name: "EASYTRIEVE PLUS", is_approved: true},
{name: "ECMAScript", is_approved: true},
{name: "Edinburgh IMP", is_approved: true},
{name: "EGL", is_approved: true},
{name: "Eiffel", is_approved: true},
{name: "ELAN", is_approved: true},
{name: "Elixir", is_approved: true},
{name: "Elm", is_approved: true},
{name: "Emacs Lisp", is_approved: true},
{name: "Emerald", is_approved: true},
{name: "Epigram", is_approved: true},
{name: "EPL", is_approved: true},
{name: "Erlang", is_approved: true},
{name: "es", is_approved: true},
{name: "Escapade", is_approved: true},
{name: "Escher", is_approved: true},
{name: "ESPOL", is_approved: true},
{name: "Esterel", is_approved: true},
{name: "Etoys", is_approved: true},
{name: "Euclid", is_approved: true},
{name: "Euler", is_approved: true},
{name: "Euphoria", is_approved: true},
{name: "EusLisp Robot Programming Language", is_approved: true},
{name: "CMS EXEC", is_approved: true},
{name: "EXEC 2", is_approved: true},
{name: "Executable UML", is_approved: true},
{name: "F", is_approved: true},
{name: "F#", is_approved: true},
{name: "Factor", is_approved: true},
{name: "Falcon", is_approved: true},
{name: "Fancy", is_approved: true},
{name: "Fantom", is_approved: true},
{name: "FAUST", is_approved: true},
{name: "Felix", is_approved: true},
{name: "Ferite", is_approved: true},
{name: "FFP", is_approved: true},
{name: "Fjölnir", is_approved: true},
{name: "FL", is_approved: true},
{name: "Flavors", is_approved: true},
{name: "Flex", is_approved: true},
{name: "FLOW-MATIC", is_approved: true},
{name: "FOCAL", is_approved: true},
{name: "FOCUS", is_approved: true},
{name: "FOIL", is_approved: true},
{name: "FORMAC", is_approved: true},
{name: "@Formula", is_approved: true},
{name: "Forth", is_approved: true},
{name: "Fortran", is_approved: true},
{name: "Fortress", is_approved: true},
{name: "FoxBase", is_approved: true},
{name: "FoxPro", is_approved: true},
{name: "FP", is_approved: true},
{name: "FPr", is_approved: true},
{name: "Franz Lisp", is_approved: true},
{name: "F-Script", is_approved: true},
{name: "FSProg", is_approved: true},
{name: "G", is_approved: true},
{name: "Google Apps Script", is_approved: true},
{name: "Game Maker Language", is_approved: true},
{name: "GameMonkey Script", is_approved: true},
{name: "GAMS", is_approved: true},
{name: "GAP", is_approved: true},
{name: "G-code", is_approved: true},
{name: "Genie", is_approved: true},
{name: "GDL", is_approved: true},
{name: "Gibiane", is_approved: true},
{name: "GJ", is_approved: true},
{name: "GEORGE", is_approved: true},
{name: "GLSL", is_approved: true},
{name: "GNU E", is_approved: true},
{name: "GM", is_approved: true},
{name: "Go", is_approved: true},
{name: "Go!", is_approved: true},
{name: "GOAL", is_approved: true},
{name: "Gödel", is_approved: true},
{name: "Godiva", is_approved: true},
{name: "GOM (Good Old Mad)", is_approved: true},
{name: "Goo", is_approved: true},
{name: "Gosu", is_approved: true},
{name: "GOTRAN", is_approved: true},
{name: "GPSS", is_approved: true},
{name: "GraphTalk", is_approved: true},
{name: "GRASS", is_approved: true},
{name: "Groovy", is_approved: true},
{name: "Hack (programming language)", is_approved: true},
{name: "HAL/S", is_approved: true},
{name: "Hamilton C shell", is_approved: true},
{name: "Harbour", is_approved: true},
{name: "Hartmann pipelines", is_approved: true},
{name: "Haskell", is_approved: true},
{name: "Haxe", is_approved: true},
{name: "High Level Assembly", is_approved: true},
{name: "HLSL", is_approved: true},
{name: "Hop", is_approved: true},
{name: "Hope", is_approved: true},
{name: "Hugo", is_approved: true},
{name: "Hume", is_approved: true},
{name: "HyperTalk", is_approved: true},
{name: "IBM Basic assembly language", is_approved: true},
{name: "IBM HAScript", is_approved: true},
{name: "IBM Informix-4GL", is_approved: true},
{name: "IBM RPG", is_approved: true},
{name: "ICI", is_approved: true},
{name: "Icon", is_approved: true},
{name: "Id", is_approved: true},
{name: "IDL", is_approved: true},
{name: "Idris", is_approved: true},
{name: "IMP", is_approved: true},
{name: "Inform", is_approved: true},
{name: "Io", is_approved: true},
{name: "Ioke", is_approved: true},
{name: "IPL", is_approved: true},
{name: "IPTSCRAE", is_approved: true},
{name: "ISLISP", is_approved: true},
{name: "ISPF", is_approved: true},
{name: "ISWIM", is_approved: true},
{name: "J", is_approved: true},
{name: "J#", is_approved: true},
{name: "J++", is_approved: true},
{name: "JADE", is_approved: true},
{name: "Jako", is_approved: true},
{name: "JAL", is_approved: true},
{name: "Janus", is_approved: true},
{name: "JASS", is_approved: true},
{name: "Java", is_approved: true},
{name: "JavaScript", is_approved: true},
{name: "JCL", is_approved: true},
{name: "JEAN", is_approved: true},
{name: "Join Java", is_approved: true},
{name: "JOSS", is_approved: true},
{name: "Joule", is_approved: true},
{name: "JOVIAL", is_approved: true},
{name: "Joy", is_approved: true},
{name: "JScript", is_approved: true},
{name: "JScript .NET", is_approved: true},
{name: "JavaFX Script", is_approved: true},
{name: "Julia", is_approved: true},
{name: "Jython", is_approved: true},
{name: "K", is_approved: true},
{name: "Kaleidoscope", is_approved: true},
{name: "Karel", is_approved: true},
{name: "Karel++", is_approved: true},
{name: "KEE", is_approved: true},
{name: "Kixtart", is_approved: true},
{name: "KIF", is_approved: true},
{name: "Kojo", is_approved: true},
{name: "Kotlin", is_approved: true},
{name: "KRC", is_approved: true},
{name: "KRL", is_approved: true},
{name: "KUKA", is_approved: true},
{name: "KRYPTON", is_approved: true},
{name: "L", is_approved: true},
{name: "L# .NET", is_approved: true},
{name: "LabVIEW", is_approved: true},
{name: "Ladder", is_approved: true},
{name: "Lagoona", is_approved: true},
{name: "LANSA", is_approved: true},
{name: "Lasso", is_approved: true},
{name: "LaTeX", is_approved: true},
{name: "Lava", is_approved: true},
{name: "LC-3", is_approved: true},
{name: "Leda", is_approved: true},
{name: "Legoscript", is_approved: true},
{name: "LIL", is_approved: true},
{name: "LilyPond", is_approved: true},
{name: "Limbo", is_approved: true},
{name: "Limnor", is_approved: true},
{name: "LINC", is_approved: true},
{name: "Lingo", is_approved: true},
{name: "Linoleum", is_approved: true},
{name: "LIS", is_approved: true},
{name: "LISA", is_approved: true},
{name: "Lisaac", is_approved: true},
{name: "Lisp", is_approved: true},
{name: "Lite-C", is_approved: true},
{name: "Lithe", is_approved: true},
{name: "Little b", is_approved: true},
{name: "Logo", is_approved: true},
{name: "Logtalk", is_approved: true},
{name: "LPC", is_approved: true},
{name: "LSE", is_approved: true},
{name: "LSL", is_approved: true},
{name: "LiveCode", is_approved: true},
{name: "LiveScript", is_approved: true},
{name: "Lua", is_approved: true},
{name: "Lucid", is_approved: true},
{name: "Lustre", is_approved: true},
{name: "LYaPAS", is_approved: true},
{name: "Lynx", is_approved: true},
{name: "M2001", is_approved: true},
{name: "M4", is_approved: true},
{name: "Machine code", is_approved: true},
{name: "MAD", is_approved: true},
{name: "MAD/I", is_approved: true},
{name: "Magik", is_approved: true},
{name: "Magma", is_approved: true},
{name: "make", is_approved: true},
{name: "Maple", is_approved: true},
{name: "MAPPER", is_approved: true},
{name: "MARK-IV", is_approved: true},
{name: "Mary", is_approved: true},
{name: "MASM Microsoft Assembly x86", is_approved: true},
{name: "Mathematica", is_approved: true},
{name: "MATLAB", is_approved: true},
{name: "Maxima", is_approved: true},
{name: "Macsyma", is_approved: true},
{name: "Max", is_approved: true},
{name: "MaxScript", is_approved: true},
{name: "Maya (MEL)", is_approved: true},
{name: "MDL", is_approved: true},
{name: "Mercury", is_approved: true},
{name: "Mesa", is_approved: true},
{name: "Metacard", is_approved: true},
{name: "Metafont", is_approved: true},
{name: "MetaL", is_approved: true},
{name: "Microcode", is_approved: true},
{name: "MicroScript", is_approved: true},
{name: "MIIS", is_approved: true},
{name: "MillScript", is_approved: true},
{name: "MIMIC", is_approved: true},
{name: "Mirah", is_approved: true},
{name: "Miranda", is_approved: true},
{name: "MIVA Script", is_approved: true},
{name: "ML", is_approved: true},
{name: "Moby", is_approved: true},
{name: "Model 204", is_approved: true},
{name: "Modelica", is_approved: true},
{name: "Modula", is_approved: true},
{name: "Modula-2", is_approved: true},
{name: "Modula-3", is_approved: true},
{name: "Mohol", is_approved: true},
{name: "MOO", is_approved: true},
{name: "Mortran", is_approved: true},
{name: "Mouse", is_approved: true},
{name: "MPD", is_approved: true},
{name: "CIL", is_approved: true},
{name: "MSL", is_approved: true},
{name: "MUMPS", is_approved: true},
{name: "NASM", is_approved: true},
{name: "NATURAL", is_approved: true},
{name: "Napier88", is_approved: true},
{name: "Neko", is_approved: true},
{name: "Nemerle", is_approved: true},
{name: "nesC", is_approved: true},
{name: "NESL", is_approved: true},
{name: "Net.Data", is_approved: true},
{name: "NetLogo", is_approved: true},
{name: "NetRexx", is_approved: true},
{name: "NewLISP", is_approved: true},
{name: "NEWP", is_approved: true},
{name: "Newspeak", is_approved: true},
{name: "NewtonScript", is_approved: true},
{name: "NGL", is_approved: true},
{name: "Nial", is_approved: true},
{name: "Nice", is_approved: true},
{name: "Nickle", is_approved: true},
{name: "NPL", is_approved: true},
{name: "Not eXactly C", is_approved: true},
{name: "Not Quite C", is_approved: true},
{name: "NSIS", is_approved: true},
{name: "Nu", is_approved: true},
{name: "NWScript", is_approved: true},
{name: "NXT-G", is_approved: true},
{name: "o:XML", is_approved: true},
{name: "Oak", is_approved: true},
{name: "Oberon", is_approved: true},
{name: "Obix", is_approved: true},
{name: "OBJ2", is_approved: true},
{name: "Object Lisp", is_approved: true},
{name: "ObjectLOGO", is_approved: true},
{name: "Object REXX", is_approved: true},
{name: "Object Pascal", is_approved: true},
{name: "Objective-C", is_approved: true},
{name: "Objective-J", is_approved: true},
{name: "Obliq", is_approved: true},
{name: "Obol", is_approved: true},
{name: "OCaml", is_approved: true},
{name: "occam", is_approved: true},
{name: "occam-π", is_approved: true},
{name: "Octave", is_approved: true},
{name: "OmniMark", is_approved: true},
{name: "Onyx", is_approved: true},
{name: "Opa", is_approved: true},
{name: "Opal", is_approved: true},
{name: "OpenCL", is_approved: true},
{name: "OpenEdge ABL", is_approved: true},
{name: "OPL", is_approved: true},
{name: "OPS5", is_approved: true},
{name: "OptimJ", is_approved: true},
{name: "Orc", is_approved: true},
{name: "ORCA/Modula-2", is_approved: true},
{name: "Oriel", is_approved: true},
{name: "Orwell", is_approved: true},
{name: "Oxygene", is_approved: true},
{name: "Oz", is_approved: true},
{name: "P#", is_approved: true},
{name: "ParaSail (programming language)", is_approved: true},
{name: "PARI/GP", is_approved: true},
{name: "Pascal", is_approved: true},
{name: "Pawn", is_approved: true},
{name: "PCASTL", is_approved: true},
{name: "PCF", is_approved: true},
{name: "PEARL", is_approved: true},
{name: "PeopleCode", is_approved: true},
{name: "Perl", is_approved: true},
{name: "PDL", is_approved: true},
{name: "PHP", is_approved: true},
{name: "Phrogram", is_approved: true},
{name: "Pico", is_approved: true},
{name: "Picolisp", is_approved: true},
{name: "Pict", is_approved: true},
{name: "Pike", is_approved: true},
{name: "PIKT", is_approved: true},
{name: "PILOT", is_approved: true},
{name: "Pipelines", is_approved: true},
{name: "Pizza", is_approved: true},
{name: "PL-11", is_approved: true},
{name: "PL/0", is_approved: true},
{name: "PL/B", is_approved: true},
{name: "PL/C", is_approved: true},
{name: "PL/I", is_approved: true},
{name: "PL/M", is_approved: true},
{name: "PL/P", is_approved: true},
{name: "PL/SQL", is_approved: true},
{name: "PL360", is_approved: true},
{name: "PLANC", is_approved: true},
{name: "Plankalkül", is_approved: true},
{name: "Planner", is_approved: true},
{name: "PLEX", is_approved: true},
{name: "PLEXIL", is_approved: true},
{name: "Plus", is_approved: true},
{name: "POP-11", is_approved: true},
{name: "PostScript", is_approved: true},
{name: "PortablE", is_approved: true},
{name: "Powerhouse", is_approved: true},
{name: "PowerBuilder", is_approved: true},
{name: "PowerShell", is_approved: true},
{name: "PPL", is_approved: true},
{name: "Processing", is_approved: true},
{name: "Processing.js", is_approved: true},
{name: "Prograph", is_approved: true},
{name: "PROIV", is_approved: true},
{name: "Prolog", is_approved: true},
{name: "PROMAL", is_approved: true},
{name: "Promela", is_approved: true},
{name: "PROSE modeling language", is_approved: true},
{name: "PROTEL", is_approved: true},
{name: "ProvideX", is_approved: true},
{name: "Pro*C", is_approved: true},
{name: "Pure", is_approved: true},
{name: "Python", is_approved: true},
{name: "Q (equational programming language)", is_approved: true},
{name: "Q (programming language from Kx Systems)", is_approved: true},
{name: "Qalb", is_approved: true},
{name: "Qi", is_approved: true},
{name: "QtScript", is_approved: true},
{name: "QuakeC", is_approved: true},
{name: "QPL", is_approved: true},
{name: "R", is_approved: true},
{name: "R++", is_approved: true},
{name: "Racket", is_approved: true},
{name: "RAPID", is_approved: true},
{name: "Rapira", is_approved: true},
{name: "Ratfiv", is_approved: true},
{name: "Ratfor", is_approved: true},
{name: "rc", is_approved: true},
{name: "REBOL", is_approved: true},
{name: "Red", is_approved: true},
{name: "Redcode", is_approved: true},
{name: "REFAL", is_approved: true},
{name: "Reia", is_approved: true},
{name: "Revolution", is_approved: true},
{name: "rex", is_approved: true},
{name: "REXX", is_approved: true},
{name: "Rlab", is_approved: true},
{name: "RobotC", is_approved: true},
{name: "ROOP", is_approved: true},
{name: "RPG", is_approved: true},
{name: "RPL", is_approved: true},
{name: "RSL", is_approved: true},
{name: "RTL/2", is_approved: true},
{name: "Ruby", is_approved: true},
{name: "RuneScript", is_approved: true},
{name: "Rust", is_approved: true},
{name: "S", is_approved: true},
{name: "S2", is_approved: true},
{name: "S3", is_approved: true},
{name: "S-Lang", is_approved: true},
{name: "S-PLUS", is_approved: true},
{name: "SA-C", is_approved: true},
{name: "SabreTalk", is_approved: true},
{name: "SAIL", is_approved: true},
{name: "SALSA", is_approved: true},
{name: "SAM76", is_approved: true},
{name: "SAS", is_approved: true},
{name: "SASL", is_approved: true},
{name: "Sather", is_approved: true},
{name: "Sawzall", is_approved: true},
{name: "SBL", is_approved: true},
{name: "Scala", is_approved: true},
{name: "Scheme", is_approved: true},
{name: "Scilab", is_approved: true},
{name: "Scratch", is_approved: true},
{name: "Script.NET", is_approved: true},
{name: "Sed", is_approved: true},
{name: "Seed7", is_approved: true},
{name: "Self", is_approved: true},
{name: "SenseTalk", is_approved: true},
{name: "SequenceL", is_approved: true},
{name: "SETL", is_approved: true},
{name: "Shift Script", is_approved: true},
{name: "SIMPOL", is_approved: true},
{name: "Shakespeare", is_approved: true},
{name: "SIGNAL", is_approved: true},
{name: "SiMPLE", is_approved: true},
{name: "SIMSCRIPT", is_approved: true},
{name: "Simula", is_approved: true},
{name: "Simulink", is_approved: true},
{name: "SISAL", is_approved: true},
{name: "SLIP", is_approved: true},
{name: "SMALL", is_approved: true},
{name: "Smalltalk", is_approved: true},
{name: "Small Basic", is_approved: true},
{name: "SML", is_approved: true},
{name: "Snap!", is_approved: true},
{name: "SNOBOL", is_approved: true},
{name: "SPITBOL", is_approved: true},
{name: "Snowball", is_approved: true},
{name: "SOL", is_approved: true},
{name: "Span", is_approved: true},
{name: "SPARK", is_approved: true},
{name: "SPIN", is_approved: true},
{name: "SP/k", is_approved: true},
{name: "SPS", is_approved: true},
{name: "Squeak", is_approved: true},
{name: "Squirrel", is_approved: true},
{name: "SR", is_approved: true},
{name: "S/SL", is_approved: true},
{name: "Stackless Python", is_approved: true},
{name: "Starlogo", is_approved: true},
{name: "Strand", is_approved: true},
{name: "Stata", is_approved: true},
{name: "Stateflow", is_approved: true},
{name: "Subtext", is_approved: true},
{name: "SuperCollider", is_approved: true},
{name: "SuperTalk", is_approved: true},
{name: "Swift (Apple programming language)", is_approved: true},
{name: "Swift (parallel scripting language)", is_approved: true},
{name: "SYMPL", is_approved: true},
{name: "SyncCharts", is_approved: true},
{name: "SystemVerilog", is_approved: true},
{name: "T", is_approved: true},
{name: "TACL", is_approved: true},
{name: "TACPOL", is_approved: true},
{name: "TADS", is_approved: true},
{name: "TAL", is_approved: true},
{name: "Tcl", is_approved: true},
{name: "Tea", is_approved: true},
{name: "TECO", is_approved: true},
{name: "TELCOMP", is_approved: true},
{name: "TeX", is_approved: true},
{name: "TEX", is_approved: true},
{name: "TIE", is_approved: true},
{name: "Timber", is_approved: true},
{name: "TMG", is_approved: true},
{name: "Tom", is_approved: true},
{name: "TOM", is_approved: true},
{name: "Topspeed", is_approved: true},
{name: "TPU", is_approved: true},
{name: "Trac", is_approved: true},
{name: "TTM", is_approved: true},
{name: "T-SQL", is_approved: true},
{name: "TTCN", is_approved: true},
{name: "Turing", is_approved: true},
{name: "TUTOR", is_approved: true},
{name: "TXL", is_approved: true},
{name: "TypeScript", is_approved: true},
{name: "Turbo C++", is_approved: true},
{name: "Ubercode", is_approved: true},
{name: "UCSD Pascal", is_approved: true},
{name: "Umple", is_approved: true},
{name: "Unicon", is_approved: true},
{name: "Uniface", is_approved: true},
{name: "UNITY", is_approved: true},
{name: "Unix shell", is_approved: true},
{name: "UnrealScript", is_approved: true},
{name: "Vala", is_approved: true},
{name: "VBA", is_approved: true},
{name: "VBScript", is_approved: true},
{name: "Verilog", is_approved: true},
{name: "VHDL", is_approved: true},
{name: "Visual Basic", is_approved: true},
{name: "Visual Basic .NET", is_approved: true},
{name: "Visual DataFlex", is_approved: true},
{name: "Visual DialogScript", is_approved: true},
{name: "Visual Fortran", is_approved: true},
{name: "Visual FoxPro", is_approved: true},
{name: "Visual J++", is_approved: true},
{name: "Visual J#", is_approved: true},
{name: "Visual Objects", is_approved: true},
{name: "Visual Prolog", is_approved: true},
{name: "VSXu", is_approved: true},
{name: "Vvvv", is_approved: true},
{name: "WATFIV, WATFOR", is_approved: true},
{name: "WebDNA", is_approved: true},
{name: "WebQL", is_approved: true},
{name: "Windows PowerShell", is_approved: true},
{name: "Winbatch", is_approved: true},
{name: "Wolfram", is_approved: true},
{name: "Wyvern", is_approved: true},
{name: "X++", is_approved: true},
{name: "X#", is_approved: true},
{name: "X10", is_approved: true},
{name: "XBL", is_approved: true},
{name: "XC", is_approved: true},
{name: "XMOS architecture", is_approved: true},
{name: "xHarbour", is_approved: true},
{name: "XL", is_approved: true},
{name: "Xojo", is_approved: true},
{name: "XOTcl", is_approved: true},
{name: "XPL", is_approved: true},
{name: "XPL0", is_approved: true},
{name: "XQuery", is_approved: true},
{name: "XSB", is_approved: true},
{name: "XSLT", is_approved: true},
{name: "XPath", is_approved: true},
{name: "Xtend", is_approved: true},
{name: "Yorick", is_approved: true},
{name: "YQL", is_approved: true},
{name: "Z notation", is_approved: true},
{name: "Zeno", is_approved: true},
{name: "ZOPL", is_approved: true},
{name: "ZPL", is_approved: true},
{name: "Web development", is_approved: true},
{name: "Linux", is_approved: true},
{name: "AWS", is_approved: true},
{name: "Docker", is_approved: true},
{name: "Arduino", is_approved: true},
]

Tag.create(skills)