slack_web_hook_url: ''
slack_app_client_id: ''
slack_app_client_secret: ''
slack_legacy_token: ''

mailgun_api_key: ''
mailchimp_api_key: ''
mail_host: 'smtp.sparkpostmail.com'
mail_port: '587'
mail_domain: 'menadevs.com'
mail_username: 'SMTP_Injection'
mail_password: ''
app_email: 'no-reply@menadevs.com'
admin_email: 'info@menadevs.com'